import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";

import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  variable: "--font-manrope",
});


export const metadata: Metadata = {
  title: "mireyags",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={manrope.className}>
      <body className={`font-manrope antialiased`}>
        <AuthProvider>
          <AppProvider>

            {children}
            <Toaster />

          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
